<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>
<!-- corpus_to_background.xslt: XML -> Prolog cooccur facts. ZERO PYTHON. -->
<xsl:template match="/ontology">
% AUTO-GENERATED BY XSLT FROM <xsl:value-of select="@name"/>
:- dynamic member/2, induced_rule/2, cooccur/3.
<xsl:for-each select="concepts/concept/member">
cooccur('<xsl:value-of select="@word"/>','<xsl:value-of select="../@id"/>',<xsl:value-of select="@strength"/>).
member('<xsl:value-of select="@word"/>', <xsl:value-of select="../@id"/>).
word('<xsl:value-of select="@word"/>').
</xsl:for-each>
<xsl:for-each select="concepts/concept">
concept(<xsl:value-of select="@id"/>).
is_a(<xsl:value-of select="@id"/>, <xsl:value-of select="@is_a"/>).
</xsl:for-each>
</xsl:template>
</xsl:stylesheet>
