<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>
<!-- ontology_to_induction.xslt: XSLT that GENERATES the Prolog ILP engine.
     Meta-trick: the system generates its own inference engine from ontology.xml.
     ontology.xml --(this XSLT)--> ontology_induction_generated.pl --(swipl)--> induced rules -->
<xsl:template match="/ontology">
% === AUTO-GENERATED BY XSLT FROM <xsl:value-of select="@name"/> ===
% File: ontology_induction_generated.pl
% Pipeline: ontology.xml --(XSLT)--> induction.pl  ZERO PYTHON

:- dynamic member/2, induced_rule/2, cooccur/3.

% --- Background co-occurrence facts ---
<xsl:for-each select="concepts/concept/member">cooccur('<xsl:value-of select="@word"/>','<xsl:value-of select="../@id"/>',<xsl:value-of select="@strength"/>).
</xsl:for-each>
% --- Concept list ---
<xsl:for-each select="concepts/concept">concept(<xsl:value-of select="@id"/>).
is_a(<xsl:value-of select="@id"/>, <xsl:value-of select="@is_a"/>).
<xsl:for-each select="member">member('<xsl:value-of select="@word"/>', <xsl:value-of select="../@id"/>).
</xsl:for-each>
</xsl:for-each>

% --- ILP Engine (pure Prolog, generated by XSLT) ---
candidate_score(Concept, Context, Precision, Recall, F1, PosCovered) :-
    findall(W, member(W, Concept), Pos), length(Pos, PosTotal), PosTotal > 0,
    findall(W, (member(W, Concept), cooccur(W, Context, _)), Covered), length(Covered, PosCovered),
    findall(W, cooccur(W, Context, _), All), length(All, AllTotal),
    (AllTotal > 0 -> Precision is PosCovered / AllTotal ; Precision = 0),
    Recall is PosCovered / PosTotal,
    (Precision + Recall > 0 -> F1 is 2*Precision*Recall/(Precision+Recall) ; F1 = 0).

best_rule_for_concept(Concept, BestContext, BestF1) :-
    setof(Context, W^Cnt^cooccur(W, Context, Cnt), Contexts),
    findall((F1,Context), candidate_score(Concept, Context, _, _, F1, _), Scores),
    Scores \= [], max_member((BestF1, BestContext), Scores).

induce_rules :-
    retractall(induced_rule(_,_)),
    forall(concept(C),
        ( best_rule_for_concept(C, Context, F1), F1 > 0.2,
          assertz(induced_rule(C, Context)),
          format("Induced: is_a(W, ~w) :- cooccur(W, '~w'). F1=~2f~n", [C, Context, F1])
        ; format("No rule for ~w (insufficient evidence)~n", [C])
        )).

propose_new_members :-
    forall(
        ( cooccur(W, Context, Cnt), Cnt >= 1,
          induced_rule(Concept, Context),
          \+ member(W, Concept), \+ W = Concept ),
        format("Propose: ~w should be is_a(~w) because cooccurs with '~w' cnt=~w~n",
               [W, Concept, Context, Cnt])).

:- format("=== ILP Induction Generated by XSLT from ~w ===~n", ['<xsl:value-of select="@name"/>']),
   induce_rules, format("~n=== Proposing ===~n"), propose_new_members.
</xsl:template>
</xsl:stylesheet>
